import './style.css';

type Engine = { analyze_text(s:string):string; monte_carlo_pi(n:number,seed:number):string; process_signal(a:Float64Array,s:number):Float64Array; generate_terrain(w:number,h:number,s:number):Uint8Array; sort_f64(a:Float64Array):Float64Array; engine_manifest():string };
let engine:Engine|null=null, bootAt=performance.now(), seed=4815;
const $=<T extends Element=HTMLElement>(q:string)=>document.querySelector(q) as T;
const fmt=(n:number,d=1)=>n.toLocaleString(undefined,{maximumFractionDigits:d});

$('#app').innerHTML=`
<div class="noise"></div><header><a class="brand" href="#"><span class="mark">W</span><span>WASMFORGE</span><i>LAB/01</i></a><div class="header-center"><span class="pulse"></span><span id="connection">INITIALIZING RUNTIME</span></div><div class="header-actions"><button class="icon-btn" id="theme" aria-label="Toggle appearance">◐</button><button class="command" id="cmdBtn"><kbd>⌘</kbd> Command <kbd>K</kbd></button><div class="avatar">RS</div></div></header>
<aside><nav><div class="nav-label">WORKSPACE</div><button class="nav active" data-view="overview"><span>⌁</span>Overview<em>01</em></button><button class="nav" data-view="text"><span>¶</span>Text intelligence</button><button class="nav" data-view="compute"><span>△</span>Compute lab</button><button class="nav" data-view="terrain"><span>▦</span>Visual pipeline</button><div class="nav-label gap">PLATFORM</div><button class="nav" data-view="architecture"><span>⌘</span>Architecture</button><button class="nav" data-view="jobs"><span>⇄</span>Native jobs<i id="jobDot"></i></button></nav><div class="aside-card"><div class="aside-top"><span>RUNTIME</span><b>LIVE</b></div><strong id="runtimeVersion">Rust / Wasm</strong><div class="meter"><i></i></div><small id="wasmSize">Loading binary…</small></div><div class="aside-user"><div class="avatar muted">WS</div><div><b>WSL Workspace</b><small>Local development</small></div><span>•••</span></div></aside>
<main>
<section class="hero"><div><div class="eyebrow">RUST-POWERED SYSTEMS LABORATORY</div><h1>Move the <em>hard parts</em><br>behind the boundary.</h1><p>A production-minded proving ground for native Rust services and browser-side WebAssembly. One shell. Two runtimes. Zero hand-waving.</p></div><div class="hero-status"><div class="orbit"><i></i><i></i><span>W</span></div><div><small>COMPUTE CORE</small><strong id="coreStatus">BOOTING</strong><span id="bootTime">—</span></div></div></section>
<section class="metrics"><article><div><span class="metric-icon lime">ϟ</span><small>WASM STARTUP</small></div><strong id="startupMetric">—</strong><em>module + bindings</em></article><article><div><span class="metric-icon blue">↯</span><small>NATIVE API</small></div><strong id="apiMetric">—</strong><em>round-trip / WSL</em></article><article><div><span class="metric-icon purple">◇</span><small>MEMORY MODEL</small></div><strong>SAFE</strong><em>ownership checked</em></article><article><div><span class="metric-icon orange">◎</span><small>BOUNDARY CALLS</small></div><strong id="callsMetric">0</strong><em>batched operations</em></article></section>
<div class="section-title"><div><span>LIVE EXPERIMENTS</span><p>Real workloads. Measured locally. No simulated results.</p></div><button id="runAll">RUN ALL BENCHMARKS <b>→</b></button></div>
<section class="grid">
<article class="panel text-panel"><div class="panel-head"><div><span class="tag">01 / PARSER</span><h2>Text intelligence</h2></div><span class="engine-pill">WASM CORE</span></div><textarea id="textInput" spellcheck="false">Rust and WebAssembly form a compact, deterministic compute layer. Keep the interface flexible; move parsing, simulation, transforms, and sensitive logic behind one carefully designed boundary.</textarea><div class="text-stats"><div><small>WORDS</small><b id="words">—</b></div><div><small>UNIQUE</small><b id="unique">—</b></div><div><small>DENSITY</small><b id="density">—</b></div><div><small>FINGERPRINT</small><b id="fingerprint">—</b></div></div><div class="terms" id="terms"></div><div class="panel-foot"><span id="parseTime">Awaiting engine</span><button id="analyze">ANALYZE <b>→</b></button></div></article>
<article class="panel terrain-panel"><div class="panel-head"><div><span class="tag">02 / GENERATIVE</span><h2>Procedural terrain</h2></div><span class="engine-pill">RGBA BUFFER</span></div><div class="canvas-wrap"><canvas id="terrain" width="720" height="330"></canvas><div class="canvas-hud"><span>SEED <b id="seed">4815</b></span><span>288 KB TRANSFER</span></div></div><div class="terrain-controls"><label>WORLD SEED<input id="seedInput" type="range" min="1" max="9999" value="4815"></label><button id="regenerate">REGENERATE</button></div><div class="panel-foot"><span id="terrainTime">Noise octaves execute inside Wasm</span><span class="legend"><i></i> Typed-array boundary</span></div></article>
<article class="panel compute-panel"><div class="panel-head"><div><span class="tag">03 / COMPUTE</span><h2>Monte Carlo π</h2></div><span class="engine-pill">DETERMINISTIC</span></div><div class="pi-result"><div class="pi-mark">π</div><div><small>ESTIMATE</small><strong id="pi">3.——</strong><span id="piError">Choose a sample size</span></div></div><div class="sample-options"><button data-n="100000">100K</button><button data-n="1000000" class="selected">1M</button><button data-n="5000000">5M</button></div><button class="primary" id="runPi">EXECUTE 1,000,000 SAMPLES <b>→</b></button><div class="spark" id="spark"></div></article>
<article class="panel stack-panel"><div class="panel-head"><div><span class="tag">04 / TOPOLOGY</span><h2>Runtime fabric</h2></div><span class="engine-pill native">DUAL RUNTIME</span></div><div class="topology"><div class="node"><i class="lime">TS</i><div><b>Product shell</b><small>Vite + TypeScript</small></div><em>UI</em></div><div class="flow"><i></i><span>typed ABI</span></div><div class="node active-node"><i class="purple">W</i><div><b>Compute core</b><small>wasm32-unknown</small></div><em>CLIENT</em></div><div class="flow"><i></i><span>HTTP / WS</span></div><div class="node"><i class="orange">RS</i><div><b>Axum service</b><small>Native Linux / WSL</small></div><em>SERVER</em></div></div><div class="capabilities" id="capabilities"></div></article>
</section>
<footer><span>WASMFORGE <b>© 2026</b></span><span><i></i> ALL SYSTEMS NOMINAL</span><span>RUST 2024 · WASM · WSL2</span></footer>
</main>
<div class="toast" id="toast"></div><dialog id="commandDialog"><div class="dialog-search"><span>⌕</span><input id="commandInput" placeholder="Type a command or experiment…"><kbd>ESC</kbd></div><div class="command-list"><small>QUICK ACTIONS</small><button data-action="all"><i>ϟ</i><span><b>Run all benchmarks</b><em>Exercise every Rust/Wasm path</em></span><kbd>↵</kbd></button><button data-action="terrain"><i>▦</i><span><b>Regenerate world</b><em>Create a new procedural terrain</em></span></button><button data-action="job"><i>⇄</i><span><b>Queue native job</b><em>Dispatch work to Rust/Axum on WSL</em></span></button></div></dialog>`;

let calls=0, selectedN=1_000_000;
function count(){ $('#callsMetric').textContent=String(++calls); }
function toast(s:string){const e=$('#toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
async function boot(){
 const t=performance.now();
 try { const wasmUrl='/pkg/wasmforge_engine.js'; const mod=await import(/* @vite-ignore */ wasmUrl); await mod.default(); engine=mod as unknown as Engine; const ms=performance.now()-t;
  $('#startupMetric').textContent=`${ms.toFixed(1)} ms`;$('#coreStatus').textContent='ONLINE';$('#bootTime').textContent=`READY IN ${ms.toFixed(0)} MS`;$('#connection').textContent='WASM CORE ONLINE';document.body.classList.add('online');
  const manifest=JSON.parse(engine.engine_manifest()); count(); $('#runtimeVersion').textContent=`${manifest.name} v${manifest.version}`;$('#capabilities').innerHTML=manifest.capabilities.map((x:string)=>`<span>${x}</span>`).join('');
  analyze();generateTerrain();
 } catch(e){console.error(e);$('#coreStatus').textContent='FALLBACK';$('#connection').textContent='WASM BUILD REQUIRED';toast('Run npm run build:wasm to activate the compute core');}
 probeApi();connectStream();
}
async function probeApi(){const t=performance.now();try{const r=await fetch('/api/health');if(!r.ok)throw 0;await r.json();$('#apiMetric').textContent=`${(performance.now()-t).toFixed(1)} ms`;}catch{$('#apiMetric').textContent='DEV MODE';}}
function analyze(){if(!engine)return;const t=performance.now();const a=JSON.parse(engine.analyze_text(($('#textInput') as HTMLTextAreaElement).value));count();$('#words').textContent=fmt(a.words,0);$('#unique').textContent=fmt(a.unique_words,0);$('#density').textContent=`${(a.lexical_density*100).toFixed(0)}%`;$('#fingerprint').textContent=a.fingerprint.slice(0,8);$('#terms').innerHTML=a.top_terms.slice(0,6).map(([w,n]:[string,number])=>`<span>${w}<b>${n}</b></span>`).join('');$('#parseTime').textContent=`${a.bytes} bytes · ${(performance.now()-t).toFixed(2)} ms · one boundary call`;}
function generateTerrain(){if(!engine)return;const c=$<HTMLCanvasElement>('#terrain'),ctx=c.getContext('2d')!,t=performance.now();const pixels=engine.generate_terrain(c.width,c.height,seed);count();ctx.putImageData(new ImageData(new Uint8ClampedArray(pixels),c.width,c.height),0,0);$('#terrainTime').textContent=`Generated ${fmt(c.width*c.height,0)} pixels in ${(performance.now()-t).toFixed(1)} ms`;}
function runPi(){if(!engine)return;const t=performance.now();const r=JSON.parse(engine.monte_carlo_pi(selectedN,seed));count();const ms=performance.now()-t;$('#pi').textContent=r.estimate.toFixed(8);$('#piError').textContent=`Δ ${r.error.toExponential(2)} · ${ms.toFixed(1)} ms`;const spark=$('#spark');spark.innerHTML=Array.from({length:34},(_,i)=>`<i style="height:${16+((i*17+seed)%42)}%;animation-delay:${i*12}ms"></i>`).join('');toast(`${fmt(selectedN,0)} samples completed in ${ms.toFixed(1)} ms`);}
async function queueJob(){try{const r=await fetch('/api/jobs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'proof-of-concept',payload:{seed}})});if(!r.ok)throw 0;const j=await r.json();$('#jobDot').classList.add('on');toast(`Native job ${j.id.slice(0,8)} queued`);}catch{toast('Native API unavailable — start the Axum server');}}
function connectStream(){try{const p=location.protocol==='https:'?'wss':'ws';const ws=new WebSocket(`${p}://${location.host}/api/stream`);ws.onopen=()=>{$('#connection').textContent='DUAL RUNTIME CONNECTED'};ws.onmessage=e=>{const d=JSON.parse(e.data);document.documentElement.style.setProperty('--load',String(d.load))};}catch{}}
$('#analyze').addEventListener('click',analyze);$('#textInput').addEventListener('input',()=>{clearTimeout((window as any)._a);(window as any)._a=setTimeout(analyze,180)});$('#regenerate').addEventListener('click',()=>{seed=(seed*1664525+1013904223)>>>0;seed=seed%9999+1;($<HTMLInputElement>('#seedInput')).value=String(seed);$('#seed').textContent=String(seed);generateTerrain()});$('#seedInput').addEventListener('input',e=>{seed=+(e.target as HTMLInputElement).value;$('#seed').textContent=String(seed)});$('#seedInput').addEventListener('change',generateTerrain);$('#runPi').addEventListener('click',runPi);
document.querySelectorAll<HTMLButtonElement>('[data-n]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-n]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectedN=+b.dataset.n!;$('#runPi').innerHTML=`EXECUTE ${fmt(selectedN,0)} SAMPLES <b>→</b>`});
async function runAll(){analyze();generateTerrain();await new Promise(r=>setTimeout(r,80));runPi();probeApi();toast('Full systems exercise complete')};$('#runAll').addEventListener('click',runAll);
const dlg=$<HTMLDialogElement>('#commandDialog');$('#cmdBtn').addEventListener('click',()=>dlg.showModal());window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();dlg.showModal();$('#commandInput').focus()}if(e.key==='Escape')dlg.close()});dlg.addEventListener('click',e=>{if(e.target===dlg)dlg.close()});document.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(b=>b.onclick=()=>{dlg.close();if(b.dataset.action==='all')runAll();if(b.dataset.action==='terrain')$('#regenerate').dispatchEvent(new Event('click'));if(b.dataset.action==='job')queueJob()});
$('#theme').addEventListener('click',()=>document.body.classList.toggle('light'));document.querySelectorAll('.nav').forEach(n=>n.addEventListener('click',()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));n.classList.add('active');toast(`${(n as HTMLElement).innerText.trim()} module selected`)}));
boot();
